import type { TariffCodeRecord } from "@/types/tariff";

export const seedTariffCodes: TariffCodeRecord[] = [
  {
    id: "seed-610910",
    code: "6109.10",
    jurisdiction: "HS",
    title: "T-shirts, singlets and other vests, knitted or crocheted, of cotton",
    description: "Cotton knitted upper-body garments such as short-sleeve t-shirts and singlets.",
    keywords: ["t-shirt", "tee", "cotton", "knitted", "apparel", "shirt", "vest"],
    chapter: "61",
    section: "Textiles and textile articles",
    dutyRatePlaceholder: "Textile duty varies by destination; verify official tariff schedule.",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-620342",
    code: "6203.42",
    jurisdiction: "HS",
    title: "Men's or boys' trousers and shorts of cotton, not knitted",
    description: "Woven cotton trousers, bib overalls, breeches, shorts, and similar garments for men or boys.",
    keywords: ["trousers", "pants", "shorts", "cotton", "woven", "menswear", "apparel"],
    chapter: "62",
    section: "Textiles and textile articles",
    dutyRatePlaceholder: "Textile apparel rates vary; check origin and destination preferences.",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-620462",
    code: "6204.62",
    jurisdiction: "HS",
    title: "Women's or girls' trousers and shorts of cotton, not knitted",
    description: "Woven cotton trousers, shorts, and similar garments for women or girls.",
    keywords: ["trousers", "pants", "shorts", "cotton", "woven", "womenswear", "apparel"],
    chapter: "62",
    section: "Textiles and textile articles",
    dutyRatePlaceholder: "Textile apparel rates vary; verify official treatment.",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-611020",
    code: "6110.20",
    jurisdiction: "HS",
    title: "Sweaters, pullovers and similar articles, knitted or crocheted, of cotton",
    description: "Cotton knitted sweaters, pullovers, sweatshirts, cardigans, and vests.",
    keywords: ["sweater", "pullover", "sweatshirt", "cardigan", "cotton", "knitted", "apparel"],
    chapter: "61",
    section: "Textiles and textile articles",
    dutyRatePlaceholder: "Textile duty varies; validate official tariff and preference rules.",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-610443",
    code: "6104.43",
    jurisdiction: "HS",
    title: "Women's or girls' dresses, knitted or crocheted, of synthetic fibres",
    description: "Knitted dresses made mainly of synthetic fibres such as polyester.",
    keywords: ["dress", "synthetic", "polyester", "knitted", "apparel", "womenswear"],
    chapter: "61",
    section: "Textiles and textile articles",
    dutyRatePlaceholder: "Textile duty varies by fiber content and destination.",
    requiredDocuments: ["commercial invoice", "packing list", "fiber content statement"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-621143",
    code: "6211.43",
    jurisdiction: "HS",
    title: "Women's or girls' track suits and other garments of man-made fibres",
    description: "Woven outerwear and sportswear of synthetic or artificial fibres.",
    keywords: ["tracksuit", "outerwear", "sportswear", "synthetic", "polyester", "apparel"],
    chapter: "62",
    section: "Textiles and textile articles",
    dutyRatePlaceholder: "Textile duty varies; verify official tariff and quota treatment.",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-630260",
    code: "6302.60",
    jurisdiction: "HS",
    title: "Toilet linen and kitchen linen, of terry towelling or similar terry fabrics, of cotton",
    description: "Cotton terry towels and similar household textile articles.",
    keywords: ["towel", "terry", "cotton", "linen", "bath", "kitchen", "textile"],
    chapter: "63",
    section: "Textiles and textile articles",
    dutyRatePlaceholder: "Household textile rates vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-630790",
    code: "6307.90",
    jurisdiction: "HS",
    title: "Other made up textile articles",
    description: "Made-up textile articles not more specifically covered elsewhere.",
    keywords: ["textile", "fabric", "cover", "mask", "made-up", "article"],
    chapter: "63",
    section: "Textiles and textile articles",
    dutyRatePlaceholder: "Classification-sensitive residual heading; verify exact construction.",
    requiredDocuments: ["commercial invoice", "packing list", "material composition"],
    restrictionNotes: ["Residual headings should be reviewed against more specific alternatives."],
    riskLevel: "medium"
  },
  {
    id: "seed-640399",
    code: "6403.99",
    jurisdiction: "HS",
    title: "Footwear with outer soles of rubber, plastics or leather and uppers of leather",
    description: "Leather-upper footwear not covering the ankle, excluding sports footwear where separately classified.",
    keywords: ["footwear", "shoe", "leather", "rubber sole", "sneaker", "boot"],
    chapter: "64",
    section: "Footwear, headgear and related articles",
    dutyRatePlaceholder: "Footwear rates vary by upper, sole, and destination.",
    requiredDocuments: ["commercial invoice", "packing list", "material composition"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-640419",
    code: "6404.19",
    jurisdiction: "HS",
    title: "Footwear with outer soles of rubber or plastics and uppers of textile materials",
    description: "Textile-upper footwear with rubber or plastic outer soles.",
    keywords: ["footwear", "shoe", "textile", "rubber sole", "sneaker", "canvas"],
    chapter: "64",
    section: "Footwear, headgear and related articles",
    dutyRatePlaceholder: "Footwear duty varies by construction and destination.",
    requiredDocuments: ["commercial invoice", "packing list", "material composition"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-871200",
    code: "8712.00",
    jurisdiction: "HS",
    title: "Bicycles and other cycles, not motorized",
    description: "Complete non-motorized bicycles, including road, racing, mountain, and recreational cycles.",
    keywords: ["bicycle", "bike", "cycle", "road bike", "racing bike", "tarmac", "s-works", "specialized", "complete bicycle"],
    chapter: "87",
    section: "Vehicles, aircraft, vessels and associated transport equipment",
    dutyRatePlaceholder: "Bicycle duty varies by destination, origin, and whether the shipment is complete or parts.",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin", "technical specification"],
    restrictionNotes: ["Confirm whether the item is a complete bicycle, electric bicycle, frameset, or spare part before filing."],
    riskLevel: "medium"
  },
  {
    id: "seed-871491",
    code: "8714.91",
    jurisdiction: "HS",
    title: "Frames and forks, and parts thereof, for bicycles",
    description: "Bicycle frames, forks, framesets, and related cycle parts shipped separately from a complete bicycle.",
    keywords: ["frameset", "frame", "fork", "carbon frame", "carbon fiber", "carbon fibre", "tarmac", "s-works", "specialized", "bicycle part"],
    chapter: "87",
    section: "Vehicles, aircraft, vessels and associated transport equipment",
    dutyRatePlaceholder: "Bicycle parts duty varies by destination and whether parts are assembled or shipped separately.",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin", "technical specification", "material declaration"],
    restrictionNotes: ["Confirm complete-bike versus parts status and whether any electric assist, battery, or motor component is included."],
    riskLevel: "medium"
  },
  {
    id: "seed-420221",
    code: "4202.21",
    jurisdiction: "HS",
    title: "Handbags with outer surface of leather or composition leather",
    description: "Handbags and shoulder bags with leather outer surface.",
    keywords: ["handbag", "bag", "leather", "purse", "accessory"],
    chapter: "42",
    section: "Raw hides, skins, leather and articles thereof",
    dutyRatePlaceholder: "Leather goods rates vary by destination and material.",
    requiredDocuments: ["commercial invoice", "packing list", "material declaration"],
    restrictionNotes: ["Exotic leather may trigger wildlife documentation requirements."],
    riskLevel: "medium"
  },
  {
    id: "seed-420292",
    code: "4202.92",
    jurisdiction: "HS",
    title: "Containers and bags with outer surface of plastic sheeting or textile materials",
    description: "Backpacks, cases, and travel goods with textile or plastic outer surface.",
    keywords: ["bag", "backpack", "case", "textile", "plastic", "travel"],
    chapter: "42",
    section: "Raw hides, skins, leather and articles thereof",
    dutyRatePlaceholder: "Travel goods rates vary by material and destination.",
    requiredDocuments: ["commercial invoice", "packing list", "material declaration"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-854231",
    code: "8542.31",
    jurisdiction: "HS",
    title: "Electronic integrated circuits: processors and controllers",
    description: "Integrated circuits functioning as processors, controllers, microcontrollers, or microprocessors.",
    keywords: ["processor", "controller", "microchip", "integrated circuit", "semiconductor", "electronics"],
    chapter: "85",
    section: "Electrical machinery and equipment",
    dutyRatePlaceholder: "Electronics duty often low but verify destination-specific measures.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet"],
    restrictionNotes: ["Advanced chips may require export-control screening."],
    riskLevel: "medium"
  },
  {
    id: "seed-851713",
    code: "8517.13",
    jurisdiction: "HS",
    title: "Smartphones for cellular networks or other wireless networks",
    description: "Smartphones and similar wireless network telephones.",
    keywords: ["smartphone", "mobile phone", "cellular", "wireless", "electronics", "radio"],
    chapter: "85",
    section: "Electrical machinery and equipment",
    dutyRatePlaceholder: "Telecommunications goods require official tariff and regulatory review.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet", "radio conformity documentation"],
    restrictionNotes: ["Wireless/radio modules can require market conformity documentation."],
    riskLevel: "high"
  },
  {
    id: "seed-851762",
    code: "8517.62",
    jurisdiction: "HS",
    title: "Machines for reception, conversion and transmission of data",
    description: "Routers, switches, modems, gateways, and similar network communication devices.",
    keywords: ["router", "modem", "gateway", "network", "wifi", "wireless", "radio", "electronics"],
    chapter: "85",
    section: "Electrical machinery and equipment",
    dutyRatePlaceholder: "Network equipment rates vary; check radio and security measures.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet", "radio conformity documentation"],
    restrictionNotes: ["Wireless devices can require CE/UKCA/FCC or equivalent documentation."],
    riskLevel: "high"
  },
  {
    id: "seed-847130",
    code: "8471.30",
    jurisdiction: "HS",
    title: "Portable automatic data processing machines weighing not more than 10 kg",
    description: "Laptop and notebook computers with CPU, keyboard, and display in one housing.",
    keywords: ["laptop", "notebook", "computer", "portable", "electronics"],
    chapter: "84",
    section: "Machinery and mechanical appliances",
    dutyRatePlaceholder: "IT product treatment varies by destination and configuration.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet"],
    restrictionNotes: ["Embedded batteries and wireless modules may trigger additional requirements."],
    riskLevel: "medium"
  },
  {
    id: "seed-852852",
    code: "8528.52",
    jurisdiction: "HS",
    title: "Monitors capable of directly connecting to automatic data processing machines",
    description: "Computer monitors and displays designed for use with automatic data processing machines.",
    keywords: ["monitor", "display", "screen", "computer", "electronics"],
    chapter: "85",
    section: "Electrical machinery and equipment",
    dutyRatePlaceholder: "Display rates vary by technology and destination.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet"],
    restrictionNotes: ["Energy efficiency or safety conformity may be requested."],
    riskLevel: "medium"
  },
  {
    id: "seed-850440",
    code: "8504.40",
    jurisdiction: "HS",
    title: "Static converters",
    description: "Chargers, adapters, rectifiers, inverters, and power supply units.",
    keywords: ["charger", "adapter", "power supply", "converter", "inverter", "electronics"],
    chapter: "85",
    section: "Electrical machinery and equipment",
    dutyRatePlaceholder: "Electrical goods rates and safety conformity vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet", "safety conformity documentation"],
    restrictionNotes: ["Electrical safety documentation may be required."],
    riskLevel: "medium"
  },
  {
    id: "seed-850760",
    code: "8507.60",
    jurisdiction: "HS",
    title: "Lithium-ion accumulators",
    description: "Rechargeable lithium-ion batteries and battery packs.",
    keywords: ["battery", "lithium", "lithium-ion", "accumulator", "rechargeable", "e-bike", "pack"],
    chapter: "85",
    section: "Electrical machinery and equipment",
    dutyRatePlaceholder: "Battery duty and safety measures require official verification.",
    requiredDocuments: ["commercial invoice", "packing list", "UN38.3 test summary", "MSDS", "technical datasheet"],
    restrictionNotes: ["Lithium batteries can trigger dangerous goods transport, capacity, labeling, and certification requirements."],
    riskLevel: "high"
  },
  {
    id: "seed-850720",
    code: "8507.20",
    jurisdiction: "HS",
    title: "Lead-acid accumulators",
    description: "Lead-acid storage batteries including sealed lead-acid batteries.",
    keywords: ["battery", "lead-acid", "accumulator", "sealed", "rechargeable"],
    chapter: "85",
    section: "Electrical machinery and equipment",
    dutyRatePlaceholder: "Battery measures vary by destination and chemistry.",
    requiredDocuments: ["commercial invoice", "packing list", "MSDS", "technical datasheet"],
    restrictionNotes: ["Battery shipments can be subject to hazardous goods and recycling rules."],
    riskLevel: "high"
  },
  {
    id: "seed-330499",
    code: "3304.99",
    jurisdiction: "HS",
    title: "Beauty or make-up preparations and preparations for the care of the skin",
    description: "Cosmetic creams, lotions, serums, and skin-care preparations excluding medicaments.",
    keywords: ["cosmetic", "cream", "lotion", "serum", "skincare", "beauty", "makeup"],
    chapter: "33",
    section: "Prepared cosmetics and toiletries",
    dutyRatePlaceholder: "Cosmetics duties and product safety rules require destination review.",
    requiredDocuments: ["commercial invoice", "packing list", "ingredient list", "cosmetic product safety documentation"],
    restrictionNotes: ["Cosmetics may require ingredient, labeling, notification, and safety compliance checks."],
    riskLevel: "high"
  },
  {
    id: "seed-330510",
    code: "3305.10",
    jurisdiction: "HS",
    title: "Shampoos",
    description: "Hair shampoo preparations and similar hair-washing products.",
    keywords: ["shampoo", "hair", "cosmetic", "toiletry", "cleanser"],
    chapter: "33",
    section: "Prepared cosmetics and toiletries",
    dutyRatePlaceholder: "Cosmetics and toiletries duties vary; regulatory checks required.",
    requiredDocuments: ["commercial invoice", "packing list", "ingredient list", "cosmetic safety documentation"],
    restrictionNotes: ["Cosmetic labeling, ingredient, and notification rules may apply."],
    riskLevel: "high"
  },
  {
    id: "seed-340111",
    code: "3401.11",
    jurisdiction: "HS",
    title: "Soap and organic surface-active products for toilet use",
    description: "Soap bars and similar toilet-use washing products.",
    keywords: ["soap", "toilet", "cleanser", "cosmetic", "surfactant"],
    chapter: "34",
    section: "Soap, washing preparations and waxes",
    dutyRatePlaceholder: "Toiletry duty and safety requirements vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "ingredient list"],
    restrictionNotes: ["Personal care products may require labeling and ingredient compliance checks."],
    riskLevel: "high"
  },
  {
    id: "seed-210690",
    code: "2106.90",
    jurisdiction: "HS",
    title: "Food preparations not elsewhere specified or included",
    description: "Food preparations and supplements not covered by a more specific food heading.",
    keywords: ["food", "supplement", "protein", "snack", "preparation", "edible"],
    chapter: "21",
    section: "Prepared foodstuffs",
    dutyRatePlaceholder: "Food duties, VAT, and sanitary controls require official review.",
    requiredDocuments: ["commercial invoice", "packing list", "ingredient list", "health certificate", "certificate of origin"],
    restrictionNotes: ["Food products can require sanitary, labeling, ingredient, and import permit checks."],
    riskLevel: "high"
  },
  {
    id: "seed-190531",
    code: "1905.31",
    jurisdiction: "HS",
    title: "Sweet biscuits",
    description: "Sweet biscuits and similar baked food products.",
    keywords: ["biscuit", "cookie", "bakery", "food", "snack", "sweet"],
    chapter: "19",
    section: "Prepared foodstuffs",
    dutyRatePlaceholder: "Food duties and agricultural measures vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "ingredient list", "health certificate"],
    restrictionNotes: ["Food imports can be subject to sanitary controls and labeling rules."],
    riskLevel: "high"
  },
  {
    id: "seed-090121",
    code: "0901.21",
    jurisdiction: "HS",
    title: "Roasted coffee, not decaffeinated",
    description: "Roasted non-decaffeinated coffee beans or ground coffee.",
    keywords: ["coffee", "roasted", "beans", "ground", "food"],
    chapter: "09",
    section: "Coffee, tea, mate and spices",
    dutyRatePlaceholder: "Agricultural and food measures vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "phytosanitary or food safety documentation"],
    restrictionNotes: ["Food and plant-origin products may be subject to sanitary controls."],
    riskLevel: "high"
  },
  {
    id: "seed-392690",
    code: "3926.90",
    jurisdiction: "HS",
    title: "Other articles of plastics",
    description: "Plastic articles not more specifically classified elsewhere.",
    keywords: ["plastic", "article", "molded", "polypropylene", "polyethylene", "container"],
    chapter: "39",
    section: "Plastics and articles thereof",
    dutyRatePlaceholder: "Plastic goods rates vary by product function and destination.",
    requiredDocuments: ["commercial invoice", "packing list", "material declaration"],
    restrictionNotes: ["Food-contact plastic can require additional compliance review."],
    riskLevel: "low"
  },
  {
    id: "seed-392330",
    code: "3923.30",
    jurisdiction: "HS",
    title: "Carboys, bottles, flasks and similar articles of plastics",
    description: "Plastic bottles, flasks, and similar packing containers.",
    keywords: ["plastic", "bottle", "flask", "packaging", "container"],
    chapter: "39",
    section: "Plastics and articles thereof",
    dutyRatePlaceholder: "Packaging duty varies by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "material declaration"],
    restrictionNotes: ["Food-contact packaging may require material safety documentation."],
    riskLevel: "low"
  },
  {
    id: "seed-732690",
    code: "7326.90",
    jurisdiction: "HS",
    title: "Other articles of iron or steel",
    description: "Iron or steel articles not specifically provided for elsewhere.",
    keywords: ["steel", "iron", "metal", "bracket", "hardware", "article"],
    chapter: "73",
    section: "Base metals and articles of base metal",
    dutyRatePlaceholder: "Metal goods may face destination-specific duties or trade remedies.",
    requiredDocuments: ["commercial invoice", "packing list", "material declaration"],
    restrictionNotes: ["Steel goods can be subject to quotas, safeguards, or anti-dumping measures."],
    riskLevel: "medium"
  },
  {
    id: "seed-761699",
    code: "7616.99",
    jurisdiction: "HS",
    title: "Other articles of aluminium",
    description: "Aluminium articles not more specifically classified elsewhere.",
    keywords: ["aluminum", "aluminium", "metal", "profile", "part", "article"],
    chapter: "76",
    section: "Base metals and articles of base metal",
    dutyRatePlaceholder: "Aluminium measures vary by destination and form.",
    requiredDocuments: ["commercial invoice", "packing list", "material declaration"],
    restrictionNotes: ["Aluminium goods may need trade-remedy screening."],
    riskLevel: "medium"
  },
  {
    id: "seed-940360",
    code: "9403.60",
    jurisdiction: "HS",
    title: "Other wooden furniture",
    description: "Furniture made mainly of wood, excluding seats and medical furniture.",
    keywords: ["furniture", "wood", "table", "cabinet", "desk", "home"],
    chapter: "94",
    section: "Furniture, bedding, lamps and prefabricated buildings",
    dutyRatePlaceholder: "Furniture duty varies by material and destination.",
    requiredDocuments: ["commercial invoice", "packing list", "wood species declaration"],
    restrictionNotes: ["Wood products may require plant-origin or fumigation documentation."],
    riskLevel: "medium"
  },
  {
    id: "seed-940179",
    code: "9401.79",
    jurisdiction: "HS",
    title: "Seats with metal frames, not upholstered",
    description: "Seats with metal frames not covered by more specific seat categories.",
    keywords: ["chair", "seat", "metal", "furniture", "stool"],
    chapter: "94",
    section: "Furniture, bedding, lamps and prefabricated buildings",
    dutyRatePlaceholder: "Seat and furniture rates vary by construction.",
    requiredDocuments: ["commercial invoice", "packing list", "material declaration"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-491199",
    code: "4911.99",
    jurisdiction: "HS",
    title: "Other printed matter",
    description: "Printed matter not elsewhere specified, including printed cards, leaflets, and catalogs.",
    keywords: ["printed", "catalog", "leaflet", "card", "paper", "brochure"],
    chapter: "49",
    section: "Printed books, newspapers, pictures and other products",
    dutyRatePlaceholder: "Printed matter duty often low but content restrictions may apply.",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: ["Certain printed content may be restricted by destination law."],
    riskLevel: "low"
  },
  {
    id: "seed-490199",
    code: "4901.99",
    jurisdiction: "HS",
    title: "Printed books, brochures and similar printed matter",
    description: "Printed books and bound printed matter other than single sheets.",
    keywords: ["book", "brochure", "printed", "paper", "manual"],
    chapter: "49",
    section: "Printed books, newspapers, pictures and other products",
    dutyRatePlaceholder: "Books are often duty-free in some markets; verify official treatment.",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: ["Content restrictions can apply in some destinations."],
    riskLevel: "low"
  },
  {
    id: "seed-950300",
    code: "9503.00",
    jurisdiction: "HS",
    title: "Tricycles, scooters, dolls, toys, puzzles and similar recreational models",
    description: "Toys and recreational articles for children or general play.",
    keywords: ["toy", "doll", "puzzle", "scooter", "game", "children"],
    chapter: "95",
    section: "Toys, games and sports requisites",
    dutyRatePlaceholder: "Toy duty and safety requirements vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "toy safety certificate"],
    restrictionNotes: ["Children's products often require safety and labeling documentation."],
    riskLevel: "medium"
  },
  {
    id: "seed-950691",
    code: "9506.91",
    jurisdiction: "HS",
    title: "Articles and equipment for general physical exercise, gymnastics or athletics",
    description: "Fitness equipment, exercise machines, and similar athletic training articles.",
    keywords: ["fitness", "exercise", "gym", "athletic", "equipment", "sports"],
    chapter: "95",
    section: "Toys, games and sports requisites",
    dutyRatePlaceholder: "Sports equipment rates vary by material and destination.",
    requiredDocuments: ["commercial invoice", "packing list", "technical description"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-847989",
    code: "8479.89",
    jurisdiction: "HS",
    title: "Machines and mechanical appliances having individual functions",
    description: "Machines with specific individual functions not described by a more specific heading.",
    keywords: ["machine", "machinery", "appliance", "mechanical", "industrial", "function"],
    chapter: "84",
    section: "Machinery and mechanical appliances",
    dutyRatePlaceholder: "Machinery rates vary; specific function may change classification.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet"],
    restrictionNotes: ["Industrial machinery may require conformity or export-control screening."],
    riskLevel: "medium"
  },
  {
    id: "seed-841459",
    code: "8414.59",
    jurisdiction: "HS",
    title: "Fans, other than table, floor, wall, window, ceiling or roof fans",
    description: "Ventilation fans and similar air-moving equipment.",
    keywords: ["fan", "blower", "ventilation", "air", "machinery"],
    chapter: "84",
    section: "Machinery and mechanical appliances",
    dutyRatePlaceholder: "Electrical or mechanical fan rates vary by type.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet"],
    restrictionNotes: ["Electrical safety compliance may be required."],
    riskLevel: "medium"
  },
  {
    id: "seed-842121",
    code: "8421.21",
    jurisdiction: "HS",
    title: "Filtering or purifying machinery and apparatus for water",
    description: "Water filters, purifiers, and related apparatus.",
    keywords: ["water filter", "filter", "purifier", "filtration", "machinery"],
    chapter: "84",
    section: "Machinery and mechanical appliances",
    dutyRatePlaceholder: "Water filtration equipment rates vary by destination and use.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet"],
    restrictionNotes: ["Food-contact or potable-water claims may require compliance documentation."],
    riskLevel: "medium"
  },
  {
    id: "seed-901890",
    code: "9018.90",
    jurisdiction: "HS",
    title: "Medical, surgical, dental or veterinary instruments and appliances",
    description: "Medical-adjacent instruments and devices not classified in a more specific subheading.",
    keywords: ["medical", "surgical", "dental", "veterinary", "instrument", "device"],
    chapter: "90",
    section: "Optical, photographic, measuring, checking and medical instruments",
    dutyRatePlaceholder: "Medical device duties and regulatory controls require official review.",
    requiredDocuments: ["commercial invoice", "packing list", "medical device documentation", "technical file"],
    restrictionNotes: ["Medical products can require registration, conformity assessment, and importer authorization."],
    riskLevel: "high"
  },
  {
    id: "seed-902110",
    code: "9021.10",
    jurisdiction: "HS",
    title: "Orthopaedic or fracture appliances",
    description: "Orthopaedic appliances, braces, supports, and fracture appliances.",
    keywords: ["orthopedic", "orthopaedic", "brace", "medical", "support", "appliance"],
    chapter: "90",
    section: "Optical, photographic, measuring, checking and medical instruments",
    dutyRatePlaceholder: "Medical-adjacent goods require tariff and regulatory review.",
    requiredDocuments: ["commercial invoice", "packing list", "medical device documentation"],
    restrictionNotes: ["Medical device conformity and product claims must be reviewed."],
    riskLevel: "high"
  },
  {
    id: "seed-300490",
    code: "3004.90",
    jurisdiction: "HS",
    title: "Medicaments consisting of mixed or unmixed products for therapeutic or prophylactic uses",
    description: "Prepared medicines in measured doses or retail packings, excluding specified headings.",
    keywords: ["medicine", "medicament", "pharmaceutical", "drug", "therapeutic", "tablet"],
    chapter: "30",
    section: "Pharmaceutical products",
    dutyRatePlaceholder: "Pharmaceutical classification and import controls require specialist review.",
    requiredDocuments: ["commercial invoice", "packing list", "marketing authorization", "health authority documentation"],
    restrictionNotes: ["Pharmaceuticals are controlled goods and require human review."],
    riskLevel: "high"
  },
  {
    id: "seed-382499",
    code: "3824.99",
    jurisdiction: "HS",
    title: "Chemical products and preparations of the chemical or allied industries",
    description: "Chemical preparations and residual chemical products not more specifically described.",
    keywords: ["chemical", "preparation", "compound", "mixture", "industrial", "hazardous"],
    chapter: "38",
    section: "Miscellaneous chemical products",
    dutyRatePlaceholder: "Chemical duties and controls require composition-specific verification.",
    requiredDocuments: ["commercial invoice", "packing list", "MSDS", "chemical composition statement"],
    restrictionNotes: ["Chemicals may require REACH, SDS, hazardous goods, or controlled-substance screening."],
    riskLevel: "high"
  },
  {
    id: "seed-340250",
    code: "3402.50",
    jurisdiction: "HS",
    title: "Washing and cleaning preparations put up for retail sale",
    description: "Detergents and cleaning preparations for retail sale.",
    keywords: ["cleaning", "detergent", "washing", "surfactant", "chemical", "retail"],
    chapter: "34",
    section: "Soap, washing preparations and waxes",
    dutyRatePlaceholder: "Cleaning preparation rates and labeling rules vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "MSDS", "ingredient list"],
    restrictionNotes: ["Chemical labeling and safety documentation may be required."],
    riskLevel: "high"
  },
  {
    id: "seed-293399",
    code: "2933.99",
    jurisdiction: "HS",
    title: "Heterocyclic compounds with nitrogen hetero-atom(s) only",
    description: "Organic chemical compounds with nitrogen hetero-atoms, not specifically listed elsewhere.",
    keywords: ["organic chemical", "compound", "heterocyclic", "nitrogen", "chemical"],
    chapter: "29",
    section: "Organic chemicals",
    dutyRatePlaceholder: "Organic chemical classification requires exact CAS and composition review.",
    requiredDocuments: ["commercial invoice", "packing list", "MSDS", "CAS number statement"],
    restrictionNotes: ["Organic chemicals can be controlled, hazardous, or subject to registration rules."],
    riskLevel: "high"
  },
  {
    id: "seed-960329",
    code: "9603.29",
    jurisdiction: "HS",
    title: "Shaving brushes, hair brushes, nail brushes and other toilet brushes",
    description: "Personal grooming brushes and similar toilet brushes.",
    keywords: ["brush", "hair brush", "nail brush", "toilet", "grooming"],
    chapter: "96",
    section: "Miscellaneous manufactured articles",
    dutyRatePlaceholder: "Miscellaneous article rates vary by material and destination.",
    requiredDocuments: ["commercial invoice", "packing list", "material declaration"],
    restrictionNotes: ["Animal hair bristles may require review."],
    riskLevel: "low"
  },
  {
    id: "seed-701349",
    code: "7013.49",
    jurisdiction: "HS",
    title: "Glassware for table or kitchen purposes",
    description: "Glass household or kitchen articles excluding drinking glasses where separately classified.",
    keywords: ["glassware", "glass", "kitchen", "table", "bowl", "jar"],
    chapter: "70",
    section: "Glass and glassware",
    dutyRatePlaceholder: "Glassware rates vary by destination and use.",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: ["Food-contact articles may require compliance documentation."],
    riskLevel: "low"
  },
  {
    id: "seed-691200",
    code: "6912.00",
    jurisdiction: "HS",
    title: "Ceramic tableware, kitchenware and other household articles",
    description: "Ceramic tableware and kitchenware other than porcelain or china.",
    keywords: ["ceramic", "tableware", "kitchenware", "plate", "bowl", "mug"],
    chapter: "69",
    section: "Ceramic products",
    dutyRatePlaceholder: "Ceramic household goods rates vary; food-contact rules may apply.",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: ["Food-contact ceramics may require lead/cadmium compliance documentation."],
    riskLevel: "medium"
  },
  {
    id: "seed-441990",
    code: "4419.90",
    jurisdiction: "HS",
    title: "Tableware and kitchenware, of wood",
    description: "Wooden kitchen and table articles such as boards, bowls, and utensils.",
    keywords: ["wood", "kitchenware", "tableware", "cutting board", "utensil"],
    chapter: "44",
    section: "Wood and articles of wood",
    dutyRatePlaceholder: "Wood article duties and plant-origin controls vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "wood species declaration"],
    restrictionNotes: ["Wood articles may require fumigation, plant-health, or species documentation."],
    riskLevel: "medium"
  },
  {
    id: "seed-950450",
    code: "9504.50",
    jurisdiction: "HS",
    title: "Video game consoles and machines",
    description: "Video game consoles and machines other than coin-operated amusement machines.",
    keywords: ["game console", "video game", "console", "controller", "electronics"],
    chapter: "95",
    section: "Toys, games and sports requisites",
    dutyRatePlaceholder: "Console rates vary; embedded wireless or batteries may trigger review.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet"],
    restrictionNotes: ["Wireless controllers and lithium batteries can require additional documentation."],
    riskLevel: "medium"
  },
  {
    id: "seed-850811",
    code: "8508.11",
    jurisdiction: "HS",
    title: "Vacuum cleaners with self-contained electric motor, power not exceeding 1,500 W",
    description: "Household vacuum cleaners with self-contained electric motors.",
    keywords: ["vacuum", "cleaner", "appliance", "electric", "household"],
    chapter: "85",
    section: "Electrical machinery and equipment",
    dutyRatePlaceholder: "Household appliance rates and safety conformity vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet", "safety conformity documentation"],
    restrictionNotes: ["Electrical safety and energy labeling may apply."],
    riskLevel: "medium"
  },
  {
    id: "seed-841810",
    code: "8418.10",
    jurisdiction: "HS",
    title: "Combined refrigerator-freezers, fitted with separate external doors",
    description: "Household or commercial combined refrigerator-freezers.",
    keywords: ["refrigerator", "freezer", "fridge", "appliance", "cooling"],
    chapter: "84",
    section: "Machinery and mechanical appliances",
    dutyRatePlaceholder: "Appliance rates and energy rules vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet", "energy label documentation"],
    restrictionNotes: ["Refrigerants and energy efficiency rules may require review."],
    riskLevel: "medium"
  },
  {
    id: "seed-711719",
    code: "7117.19",
    jurisdiction: "HS",
    title: "Imitation jewellery of base metal",
    description: "Base-metal imitation jewelry, whether or not plated with precious metal.",
    keywords: ["jewelry", "jewellery", "imitation", "base metal", "necklace", "ring"],
    chapter: "71",
    section: "Pearls, precious stones, precious metals and imitation jewellery",
    dutyRatePlaceholder: "Jewelry rates vary by material and destination.",
    requiredDocuments: ["commercial invoice", "packing list", "material declaration"],
    restrictionNotes: ["Nickel, lead, and cadmium restrictions may apply in some markets."],
    riskLevel: "medium"
  },
  {
    id: "seed-961900",
    code: "9619.00",
    jurisdiction: "HS",
    title: "Sanitary towels, tampons, napkins and similar sanitary articles",
    description: "Sanitary articles and absorbent hygiene goods of any material.",
    keywords: ["sanitary", "hygiene", "napkin", "tampon", "diaper", "absorbent"],
    chapter: "96",
    section: "Miscellaneous manufactured articles",
    dutyRatePlaceholder: "Hygiene article rates and product rules vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "material declaration"],
    restrictionNotes: ["Consumer product safety or sanitary documentation may be requested."],
    riskLevel: "medium"
  },
  {
    id: "seed-401699",
    code: "4016.99",
    jurisdiction: "HS",
    title: "Other articles of vulcanised rubber other than hard rubber",
    description: "Rubber articles not more specifically classified elsewhere.",
    keywords: ["rubber", "vulcanized", "seal", "gasket", "article"],
    chapter: "40",
    section: "Rubber and articles thereof",
    dutyRatePlaceholder: "Rubber goods duty varies by product use and destination.",
    requiredDocuments: ["commercial invoice", "packing list", "material declaration"],
    restrictionNotes: [],
    riskLevel: "low"
  },
  {
    id: "seed-481910",
    code: "4819.10",
    jurisdiction: "HS",
    title: "Cartons, boxes and cases of corrugated paper or paperboard",
    description: "Corrugated paperboard cartons and packaging boxes.",
    keywords: ["carton", "box", "paperboard", "corrugated", "packaging"],
    chapter: "48",
    section: "Paper and paperboard",
    dutyRatePlaceholder: "Paper packaging rates vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: ["Packaging waste rules may apply in some markets."],
    riskLevel: "low"
  },
  {
    id: "seed-560312",
    code: "5603.12",
    jurisdiction: "HS",
    title: "Nonwovens, weighing more than 25 g/m2 but not more than 70 g/m2",
    description: "Nonwoven textile fabric in specified weight ranges.",
    keywords: ["nonwoven", "fabric", "textile", "polypropylene", "material"],
    chapter: "56",
    section: "Textiles and textile articles",
    dutyRatePlaceholder: "Textile material rates vary by weight, fiber, and destination.",
    requiredDocuments: ["commercial invoice", "packing list", "material composition"],
    restrictionNotes: ["Medical or PPE use would require separate regulatory review."],
    riskLevel: "medium"
  },
  {
    id: "seed-853952",
    code: "8539.52",
    jurisdiction: "HS",
    title: "Light-emitting diode (LED) lamps",
    description: "LED lamps and lighting sources.",
    keywords: ["led", "lamp", "light", "bulb", "lighting", "electronics"],
    chapter: "85",
    section: "Electrical machinery and equipment",
    dutyRatePlaceholder: "Lighting rates and energy rules vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet", "safety conformity documentation"],
    restrictionNotes: ["Electrical safety and energy labeling may apply."],
    riskLevel: "medium"
  },
  {
    id: "seed-853650",
    code: "8536.50",
    jurisdiction: "HS",
    title: "Electrical switches for a voltage not exceeding 1,000 V",
    description: "Electrical switches and switching devices for low-voltage circuits.",
    keywords: ["switch", "electrical", "low voltage", "component", "electronics"],
    chapter: "85",
    section: "Electrical machinery and equipment",
    dutyRatePlaceholder: "Electrical component rates and safety rules vary by destination.",
    requiredDocuments: ["commercial invoice", "packing list", "technical datasheet"],
    restrictionNotes: ["Electrical conformity documentation may be required."],
    riskLevel: "medium"
  }
];
